[package]
name = "orbfont"
description = "Orbital font rendering"
repository = "https://gitlab.redox-os.org/redox-os/orbfont"
version = "0.1.9"
license-file = "LICENSE"
readme = "README.md"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[dependencies]
orbclient = "0.3.18"
rusttype = "0.7.3"

[features]
default = []
no_std = ["orbclient/no_std"]

[target.'cfg(not(any(feature="no_std", target_os = "redox")))'.dependencies]
font-loader = "0.7.0"
