[package]
name = "orbfont"
description = "Orbital font rendering"
repository = "https://gitlab.redox-os.org/redox-os/orbfont"
version = "0.1.9"
license-file = "LICENSE"
readme = "README.md"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[dependencies]
num-traits = { version = "0.2.6", default-features = false }
orbclient = { git = "https://gitlab.redox-os.org/redox-os/orbclient.git", branch = "no_std" }
rusttype = { git = "https://gitlab.redox-os.org/redox-os/rusttype.git", branch = "no_std", features = ["no_std"] }

[features]
default = []
no_std = []

#[target.'cfg(not(target_os = "redox"))'.dependencies]
#font-loader = "0.7.0"
